version: '3.8'

services:
  langextract-dev:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
    volumes:
      - .:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - LANGEXTRACT_API_KEY=${LANGEXTRACT_API_KEY}
    ports:
      - "8501:8501"  # Streamlit
      - "8888:8888"  # Jupyter
      - "11434:11434"  # Ollama
    command: sleep infinity
    
  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

volumes:
  ollama_data: